In [ ]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 9.7 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
from os.path import exists
from os import environ, system

In [ ]:
uploaded = files.upload()

Saving sentiment_data.csv to sentiment_data.csv

In [ ]:
df = pd.read_csv("sentiment_data.csv", encoding="utf-8")
df.head()

   Unnamed: 0                                            Comment  Sentiment
0           0  lets forget apple pay required brand new iphon...          1
1           1  nz retailers don’t even contactless credit car...          0
2           2  forever acknowledge channel help lessons ideas...          2
3           3  whenever go place doesn’t take apple pay doesn...          0
4           4  apple pay convenient secure easy use used kore...          2

In [ ]:
name_col = ["rownum", "Comment", "Sentiment"]

In [ ]:
df.columns = name_col
df.columns

Index(['rownum', 'Comment', 'Sentiment'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241145 entries, 0 to 241144
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   rownum     241145 non-null  int64
 1   Comment    240928 non-null  object
 2   Sentiment  241145 non-null  int64
dtypes: int64(2), object(1)
memory usage: 5.5+ MB

In [ ]:
df["Comment"] = df["Comment"].astype(str)

**Emojis and any char**

In [ ]:
# checking emojies
import emoji
has_emoji = df["Comment"].apply(lambda x: any(char in emoji.EMOJI_DATA for char in x))
print(has_emoji.value_counts())

Comment
False    240627
True        518
Name: count, dtype: int64

In [ ]:
has_emojiiiii = df["Comment_no_emoji"].apply(lambda x: any(char in emoji.EMOJI_DATA for char in x))
print(has_emojiiiii.value_counts())

Comment_no_emoji
False    241145
Name: count, dtype: int64

In [ ]:
# converting emojis to text
df["Comment_no_emoji"] = df["Comment"].apply(lambda x: emoji.demojize(x))

In [ ]:
# cleaning emojis format to be useable
df["Comment_no_emoji"] = df["Comment_no_emoji"].str.replace("[:_]", " ", regex=True)

In [ ]:
# for finding all types of emojis
import re
emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols
                           u"\U0001F680-\U0001F6FF"  # transport
                           u"\U0001F1E0-\U0001F1FF"  # flags
                           "]+", flags=re.UNICODE)

has_emoji_two = df["Comment_no_emoji"].apply(lambda x: bool(emoji_pattern.search(str(x))))
print(has_emoji_two.sum())

0

In [ ]:
# checking for other types of emojis
print(df[has_emoji_two == True]["Comment_no_emoji"].values)

text = df[has_emoji_two == True]["Comment_no_emoji"].iloc[0]
for c in text:
    print(c, ord(c))

[]

IndexError: single positional indexer is out-of-bounds

In [ ]:
# deleting Regional Indicator Symbols
import re
df["Comment_no_emoji"] = df["Comment_no_emoji"].apply(
    lambda x: re.sub(r'[\U0001F1E6-\U0001F1FF]', '', x))

In [ ]:
df.head(40)

,rownum,Comment,Sentiment,Comment_no_emoji
0,0,lets forget apple pay required brand new iphon...,1,lets forget apple pay required brand new iphon...
1,1,nz retailers don’t even contactless credit car...,0,nz retailers don’t even contactless credit car...
2,2,forever acknowledge channel help lessons ideas...,2,forever acknowledge channel help lessons ideas...
3,3,whenever go place doesn’t take apple pay doesn...,0,whenever go place doesn’t take apple pay doesn...
4,4,apple pay convenient secure easy use used kore...,2,apple pay convenient secure easy use used kore...
5,5,we’ve hounding bank adopt apple pay understand...,1,we’ve hounding bank adopt apple pay understand...
6,6,got apple pay south africa it’s widely accepted,2,got apple pay south africa it’s widely accepted
7,7,need apple pay physical credit card,1,need apple pay physical credit card
8,8,united states abundance retailers accept apple...,2,united states abundance retailers accept apple...
9,9,cambodia universal qr code system scan send mo...,1,cambodia universal qr code system scan send mo...
10,10,wow really went town psu test rack thats serio...,2,wow really went town psu test rack thats serio...
11,11,lab exciting thing ive seen reallly going shak...,2,lab exciting thing ive seen reallly going shak...
12,12,linus im engineer love lmg content across chan...,2,linus im engineer love lmg content across chan...
13,13,used time linus smartest guy room video clearl...,2,used time linus smartest guy room video clearl...
14,14,holy crap looking chroma systems back designin...,0,holy crap looking chroma systems back designin...
15,15,love direction channel going tech channels eve...,2,love direction channel going tech channels eve...
16,16,excited ltt lab lot content everyone seems say...,2,excited ltt lab lot content everyone seems say...
17,17,adore working relationship linus team employee...,2,adore working relationship linus team employee...
18,18,lmgs growth honestly something truly aspire co...,2,lmgs growth honestly something truly aspire co...
19,19,love people ltt added labs clearly theyre know...,2,love people ltt added labs clearly theyre know...
20,20,linus turn key lights bounce walls you’ll get ...,2,linus turn key lights bounce walls you’ll get ...
21,21,dan continues new favorite air confidence comf...,2,dan continues new favorite air confidence comf...
22,22,dan managing set soldering station one box nee...,2,dan managing set soldering station one box nee...
23,23,linus gets employees cases stuff stolen office...,2,linus gets employees cases stuff stolen office...
24,24,linus table also linus lets use chair,1,linus table also linus lets use chair
25,25,dan man saving day riley needs give theme like...,2,dan man saving day riley needs give theme like...
26,26,dan continues favourite hes like incredibly pa...,2,dan continues favourite hes like incredibly pa...
27,27,dan treasure channel long lacked mr fixit type...,2,dan treasure channel long lacked mr fixit type...
28,28,blows mind quickly dan became rock upon things...,2,blows mind quickly dan became rock upon things...
29,29,hey linus good trick streaming lights bounce w...,2,hey linus good trick streaming lights bounce w...
30,30,unstoppable experiments liquid nitrogen,2,unstoppable experiments liquid nitrogen
31,31,one best things dude never takes credit wheb a...,2,one best things dude never takes credit wheb a...
32,32,liquid nitrogen ഇതുവരെ തീർന്നില്ലേ മച്ചാനെ,1,liquid nitrogen ഇതുവരെ തീർന്നില്ലേ മച്ചാനെ
33,33,liquid nitrogen never ends poli,2,liquid nitrogen never ends poli
34,34,views likes power,2,views likes power
35,35,കേരളത്തിൽ ആദ്യമായി പെട്രോളിനെ എയ്സ് ആക്കിയ മച്...,1,കേരളത്തിൽ ആദ്യമായി പെട്രോളിനെ എയ്സ് ആക്കിയ മച്...
36,36,epozhum safety first priority goggles,2,epozhum safety first priority goggles
37,37,congratulations achieving million subscribers,2,congratulations achieving million subscribers
38,38,തന്നെ തളർത്താൻ നോക്കിയവർ പോലും അവന്റെ ഉയർച്ചയി...,1,തന്നെ തളർത്താൻ നോക്കിയവർ പോലും അവന്റെ ഉയർച്ചയി...
39,39,എത്ര എടുത്താലും തീരാത്ത liquid nitrogen,1,എത്ര എടുത്താലും തീരാത്ത liquid nitrogen

**Uppercase handling**

In [ ]:
# checking percewntage of uppercase and add to table
def uppercase_ratio(text):
    if len(text) == 0:
        return 0
    num_upper = sum(1 for c in text if c.isupper())
    return num_upper / len(text)

upper_ratio = df["Comment_no_emoji"].apply(uppercase_ratio)
print(upper_ratio.describe())

count    241145.000000
mean          0.000005
std           0.000643
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           0.192308
Name: Comment_no_emoji, dtype: float64

In [ ]:
# it was for the time that there was a column for that
# df.value_counts("upper_ratio")

In [ ]:
# for checking how many uppercase is in the column
# df["Comment"].str.isupper().value_counts()

In [ ]:
# converting the uppercase to lower
df["Comment"] = df["Comment"].apply(lambda x: str(x).lower())
df["Comment"] = df["Comment"].str.lower().str.strip()
df["Comment"] = df["Comment"].astype(str).str.lower()

In [ ]:
for text in df["Comment_no_emoji"]:
    for i in text:
        if i.isupper():
            print(repr(i))
            break

'𝗧'
'𝑻'
'𝗧'
'𝗧'
'🅻'
'🅻'
'𝗧'
'🄸'
'𝘿'
'🅻'
'𝗧'
'🅻'
'🅻'
'🅻'
'🅻'
'🅻'
'🅻'
'🅻'
'🅻'
'🅻'
'🅻'
'🅻'
'🅻'
'🅻'
'🅻'
'🅻'
'O'
'O'
'O'
'N'
'O'
'O'
'O'
'C'
'O'
'O'
'O'
'M'
'N'
'O'

In [ ]:
import unicodedata
def normalize_text(text):
    return unicodedata.normalize("NFKD", text)

df["Comment_lower"] = df["Comment_no_emoji"].apply(normalize_text)
df["Comment_lower"] = df["Comment_no_emoji"].str.lower().str.strip()

In [ ]:
import re
def remove_non_latin(text):
    return re.sub(r"[^a-zA-Z0-9\s]", "", text)
df["Comment_lower"] = df["Comment_lower"].apply(remove_non_latin)

In [ ]:
df["Comment_lower"].replace("", np.nan, inplace=True)
df.dropna(subset=["Comment_lower"], inplace=True)
df.reset_index(drop=True, inplace=True)

/tmp/ipython-input-1893595509.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Comment_lower"].replace("", np.nan, inplace=True)

In [ ]:
df.head(60)

,rownum,Comment,Sentiment,Comment_no_emoji,Comment_lower
0,0,lets forget apple pay required brand new iphon...,1,lets forget apple pay required brand new iphon...,lets forget apple pay required brand new iphon...
1,1,nz retailers don’t even contactless credit car...,0,nz retailers don’t even contactless credit car...,nz retailers dont even contactless credit card...
2,2,forever acknowledge channel help lessons ideas...,2,forever acknowledge channel help lessons ideas...,forever acknowledge channel help lessons ideas...
3,3,whenever go place doesn’t take apple pay doesn...,0,whenever go place doesn’t take apple pay doesn...,whenever go place doesnt take apple pay doesnt...
4,4,apple pay convenient secure easy use used kore...,2,apple pay convenient secure easy use used kore...,apple pay convenient secure easy use used kore...
5,5,we’ve hounding bank adopt apple pay understand...,1,we’ve hounding bank adopt apple pay understand...,weve hounding bank adopt apple pay understand ...
6,6,got apple pay south africa it’s widely accepted,2,got apple pay south africa it’s widely accepted,got apple pay south africa its widely accepted
7,7,need apple pay physical credit card,1,need apple pay physical credit card,need apple pay physical credit card
8,8,united states abundance retailers accept apple...,2,united states abundance retailers accept apple...,united states abundance retailers accept apple...
9,9,cambodia universal qr code system scan send mo...,1,cambodia universal qr code system scan send mo...,cambodia universal qr code system scan send mo...
10,10,wow really went town psu test rack thats serio...,2,wow really went town psu test rack thats serio...,wow really went town psu test rack thats serio...
11,11,lab exciting thing ive seen reallly going shak...,2,lab exciting thing ive seen reallly going shak...,lab exciting thing ive seen reallly going shak...
12,12,linus im engineer love lmg content across chan...,2,linus im engineer love lmg content across chan...,linus im engineer love lmg content across chan...
13,13,used time linus smartest guy room video clearl...,2,used time linus smartest guy room video clearl...,used time linus smartest guy room video clearl...
14,14,holy crap looking chroma systems back designin...,0,holy crap looking chroma systems back designin...,holy crap looking chroma systems back designin...
15,15,love direction channel going tech channels eve...,2,love direction channel going tech channels eve...,love direction channel going tech channels eve...
16,16,excited ltt lab lot content everyone seems say...,2,excited ltt lab lot content everyone seems say...,excited ltt lab lot content everyone seems say...
17,17,adore working relationship linus team employee...,2,adore working relationship linus team employee...,adore working relationship linus team employee...
18,18,lmgs growth honestly something truly aspire co...,2,lmgs growth honestly something truly aspire co...,lmgs growth honestly something truly aspire co...
19,19,love people ltt added labs clearly theyre know...,2,love people ltt added labs clearly theyre know...,love people ltt added labs clearly theyre know...
20,20,linus turn key lights bounce walls you’ll get ...,2,linus turn key lights bounce walls you’ll get ...,linus turn key lights bounce walls youll get m...
21,21,dan continues new favorite air confidence comf...,2,dan continues new favorite air confidence comf...,dan continues new favorite air confidence comf...
22,22,dan managing set soldering station one box nee...,2,dan managing set soldering station one box nee...,dan managing set soldering station one box nee...
23,23,linus gets employees cases stuff stolen office...,2,linus gets employees cases stuff stolen office...,linus gets employees cases stuff stolen office...
24,24,linus table also linus lets use chair,1,linus table also linus lets use chair,linus table also linus lets use chair
25,25,dan man saving day riley needs give theme like...,2,dan man saving day riley needs give theme like...,dan man saving day riley needs give theme like...
26,26,dan continues favourite hes like incredibly pa...,2,dan continues favourite hes like incredibly pa...,dan continues favourite hes like incredibly pa...
27,27,dan treasure channel long lacked mr fixit type...,2,dan treasure channel long lacked mr fixit type...,dan treasure channel long lacked mr fixit type...
28,28,blows mind quickly dan became rock upon things...,2,blows mind quickly dan became rock upon things...,blows mind quickly dan became rock upon things...
29,29,hey linus good trick streaming lights bounce w...,2,hey linus good trick streaming lights bounce w...,hey linus good trick streaming lights bounce w...
30,30,unstoppable experiments liquid nitrogen,2,unstoppable experiments liquid nitrogen,unstoppable experiments liquid nitrogen
31,31,one best things dude never takes credit wheb a...,2,one best things dude never takes credit wheb a...,one best things dude never takes credit wheb a...
32,32,liquid nitrogen ഇതുവരെ തീർന്നില്ലേ മച്ചാനെ,1,liquid nitrogen ഇതുവരെ തീർന്നില്ലേ മച്ചാനെ,liquid nitrogen
33,33,liquid nitrogen never ends poli,2,liquid nitrogen never ends poli,liquid nitrogen never ends poli
34,34,views likes power,2,views likes power,views likes power
35,35,കേരളത്തിൽ ആദ്യമായി പെട്രോളിനെ എയ്സ് ആക്കിയ മച്...,1,കേരളത്തിൽ ആദ്യമായി പെട്രോളിനെ എയ്സ് ആക്കിയ മച്...,
36,36,epozhum safety first priority goggles,2,epozhum safety first priority goggles,epozhum safety first priority goggles
37,37,congratulations achieving million subscribers,2,congratulations achieving million subscribers,congratulations achieving million subscribers
38,38,തന്നെ തളർത്താൻ നോക്കിയവർ പോലും അവന്റെ ഉയർച്ചയി...,1,തന്നെ തളർത്താൻ നോക്കിയവർ പോലും അവന്റെ ഉയർച്ചയി...,tech
39,39,എത്ര എടുത്താലും തീരാത്ത liquid nitrogen,1,എത്ര എടുത്താലും തീരാത്ത liquid nitrogen,liquid nitrogen
40,40,guys quick note need highend tech order well c...,1,guys quick note need highend tech order well c...,guys quick note need highend tech order well c...
41,41,hilarious focus group years ago best buy askin...,1,hilarious focus group years ago best buy askin...,hilarious focus group years ago best buy askin...
42,42,everyone saying i’ll throw hat well prospectiv...,2,everyone saying i’ll throw hat well prospectiv...,everyone saying ill throw hat well prospective...
43,43,shoutout oneplus phone huawei laptop getting u...,2,shoutout oneplus phone huawei laptop getting u...,shoutout oneplus phone huawei laptop getting u...
44,44,best buy want sponsor back school type video p...,1,best buy want sponsor back school type video p...,best buy want sponsor back school type video p...
45,45,items recommend pretty pricey student im stude...,1,items recommend pretty pricey student im stude...,items recommend pretty pricey student im stude...
46,46,dont necessarily need highend latest tech univ...,2,dont necessarily need highend latest tech univ...,dont necessarily need highend latest tech univ...
47,47,personally feel like really touch students won...,2,personally feel like really touch students won...,personally feel like really touch students won...
48,48,hey everyone good take video love recommendati...,2,hey everyone good take video love recommendati...,hey everyone good take video love recommendati...
49,49,used galaxy tab phd lifesaver first really goo...,2,used galaxy tab phd lifesaver first really goo...,used galaxy tab phd lifesaver first really goo...
50,50,says hes year old beer wizard believe,1,says hes year old beer wizard believe,says hes year old beer wizard believe
51,51,series exactly career day shouldve interesting...,2,series exactly career day shouldve interesting...,series exactly career day shouldve interesting...
52,52,regarding cans vs bottles least germany bottle...,1,regarding cans vs bottles least germany bottle...,regarding cans vs bottles least germany bottle...
53,53,every person wired brings show act like theyve...,0,every person wired brings show act like theyve...,every person wired brings show act like theyve...
54,54,idk who’s picking people give raise,1,idk who’s picking people give raise,idk whos picking people give raise
55,55,face describing hops killed “some smell pretty...,0,face describing hops killed “some smell pretty...,face describing hops killed some smell pretty ...
56,56,seasoned craft brewery tour guide i’m glad end...,2,seasoned craft brewery tour guide i’m glad end...,seasoned craft brewery tour guide im glad ende...
57,57,guy total bro snobby wants people enjoy beer w...,2,guy total bro snobby wants people enjoy beer w...,guy total bro snobby wants people enjoy beer w...
58,58,y’all picking literal best professionals video...,2,y’all picking literal best professionals video...,yall picking literal best professionals videos...
59,59,guy face made movies voice made radio great pe...,2,guy face made movies voice made radio great pe...,guy face made movies voice made radio great pe...

**URL**

In [ ]:
# checking urls
import re
has_url = df["Comment_lower"].apply(lambda x: bool(re.search(r"http[s]?://", x)))
print(has_url.value_counts())

Comment_lower
False    241113
Name: count, dtype: int64

In [ ]:
# df["Comment"].str.contains("http").value_counts()

**CONTRACTIONS**

In [ ]:
!pip install contractions
import contractions

Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (13 kB)
Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Downloading anyascii-0.3.3-py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 6.5 MB/s eta 0:00:00
Downloading pyahocorasick-2.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 8.9 MB/s eta 0:00:00
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions
Successfully installed anyascii-0.3.3 contractions-0.1.73 pyahocorasick-2.3.0 textsearch-0.0.24

In [ ]:
# checking contractions
has_contraction = df["Comment_lower"].str.contains(r"\b\w+'\w+\b")
print(has_contraction.value_counts())

Comment_lower
False    241113
Name: count, dtype: int64

In [ ]:
# this is for handling contractions like im that will convert to i am
df["contractions"] = df["Comment_lower"].apply(lambda x: contractions.fix(x))

In [ ]:
apostrophes_cheker = ()
for text in df["Comment_lower"]:
    for i in text:
        if i in ["'", "’"]:
            apostrophes_cheker.add(i)
print(apostrophes_cheker)

NameError: name 'df' is not defined

In [ ]:
has_contraction = df["contractions"].str.contains(r"\b\w+'\w+\b", regex=True)
print(has_contraction.sum())

0

In [ ]:
# for combining all of them
# has_contraction = df["Comment"].str.contains(r"\b\w+[-']\w+\b|\b(?:don't|can't|I'm|you're)\b")

In [ ]:
# df["Comment"].str.contains("'").value_counts()

In [ ]:
df.head(10)

,rownum,Comment,Sentiment,Comment_no_emoji,Comment_lower,contractions
0,0,lets forget apple pay required brand new iphon...,1,lets forget apple pay required brand new iphon...,lets forget apple pay required brand new iphon...,let us forget apple pay required brand new iph...
1,1,nz retailers don’t even contactless credit car...,0,nz retailers don’t even contactless credit car...,nz retailers dont even contactless credit card...,nz retailers do not even contactless credit ca...
2,2,forever acknowledge channel help lessons ideas...,2,forever acknowledge channel help lessons ideas...,forever acknowledge channel help lessons ideas...,forever acknowledge channel help lessons ideas...
3,3,whenever go place doesn’t take apple pay doesn...,0,whenever go place doesn’t take apple pay doesn...,whenever go place doesnt take apple pay doesnt...,whenever go place does not take apple pay does...
4,4,apple pay convenient secure easy use used kore...,2,apple pay convenient secure easy use used kore...,apple pay convenient secure easy use used kore...,apple pay convenient secure easy use used kore...
5,5,we’ve hounding bank adopt apple pay understand...,1,we’ve hounding bank adopt apple pay understand...,weve hounding bank adopt apple pay understand ...,we have hounding bank adopt apple pay understa...
6,6,got apple pay south africa it’s widely accepted,2,got apple pay south africa it’s widely accepted,got apple pay south africa its widely accepted,got apple pay south africa its widely accepted
7,7,need apple pay physical credit card,1,need apple pay physical credit card,need apple pay physical credit card,need apple pay physical credit card
8,8,united states abundance retailers accept apple...,2,united states abundance retailers accept apple...,united states abundance retailers accept apple...,united states abundance retailers accept apple...
9,9,cambodia universal qr code system scan send mo...,1,cambodia universal qr code system scan send mo...,cambodia universal qr code system scan send mo...,cambodia universal qr code system scan send mo...

**-------------- -------------- -------------- --------------**

**Tokenization and stopword removal**

In [ ]:
!pip install contractions

Requirement already satisfied: contractions in /usr/local/lib/python3.12/dist-packages (0.1.73)
Requirement already satisfied: textsearch>=0.0.21 in /usr/local/lib/python3.12/dist-packages (from contractions) (0.0.24)
Requirement already satisfied: anyascii in /usr/local/lib/python3.12/dist-packages (from textsearch>=0.0.21->contractions) (0.3.3)
Requirement already satisfied: pyahocorasick in /usr/local/lib/python3.12/dist-packages (from textsearch>=0.0.21->contractions) (2.3.0)

In [ ]:
import contractions
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
# tokenization or splitting the word
df["tokenizing"] = df["contractions"].apply(word_tokenize)

In [ ]:
# stopwords removal
handling_stop_words = set(stopwords.words('english'))

df["stopword_removal"] = df["tokenizing"].apply(lambda words: [w for w in words if w.lower() not in handling_stop_words])

In [ ]:
# for the time if it needs to turn back to the text again
# df['clean_text'] = df['tokens'].apply(lambda words: ' '.join(words))

In [ ]:
df.loc[[55, 56, 57, 58, 59, 60, 61]]

,rownum,Comment,Sentiment,Comment_no_emoji,Comment_lower,contractions,tokenizing,stopword_removal
55,55,face describing hops killed “some smell pretty...,0,face describing hops killed “some smell pretty...,face describing hops killed some smell pretty ...,face describing hops killed some smell pretty ...,"[face, describing, hops, killed, some, smell, ...","[face, describing, hops, killed, smell, pretty..."
56,56,seasoned craft brewery tour guide i’m glad end...,2,seasoned craft brewery tour guide i’m glad end...,seasoned craft brewery tour guide im glad ende...,seasoned craft brewery tour guide i am glad en...,"[seasoned, craft, brewery, tour, guide, i, am,...","[seasoned, craft, brewery, tour, guide, glad, ..."
57,57,guy total bro snobby wants people enjoy beer w...,2,guy total bro snobby wants people enjoy beer w...,guy total bro snobby wants people enjoy beer w...,guy total bro snobby wants people enjoy beer w...,"[guy, total, bro, snobby, wants, people, enjoy...","[guy, total, bro, snobby, wants, people, enjoy..."
58,58,y’all picking literal best professionals video...,2,y’all picking literal best professionals video...,yall picking literal best professionals videos...,you all picking literal best professionals vid...,"[you, all, picking, literal, best, professiona...","[picking, literal, best, professionals, videos..."
59,59,guy face made movies voice made radio great pe...,2,guy face made movies voice made radio great pe...,guy face made movies voice made radio great pe...,guy face made movies voice made radio great pe...,"[guy, face, made, movies, voice, made, radio, ...","[guy, face, made, movies, voice, made, radio, ..."
60,60,whenever get people young enough actually unde...,0,whenever get people young enough actually unde...,whenever get people young enough actually unde...,whenever get people young enough actually unde...,"[whenever, get, people, young, enough, actuall...","[whenever, get, people, young, enough, actuall..."
61,61,live johns roasts att,2,live johns roasts att,live johns roasts att,live johns roasts att,"[live, johns, roasts, att]","[live, johns, roasts, att]"

In [ ]:
df.head(10)

,rownum,Comment,Sentiment,Comment_no_emoji,Comment_lower,contractions,tokenizing,stopword_removal
0,0,lets forget apple pay required brand new iphon...,1,lets forget apple pay required brand new iphon...,lets forget apple pay required brand new iphon...,let us forget apple pay required brand new iph...,"[let, us, forget, apple, pay, required, brand,...","[let, us, forget, apple, pay, required, brand,..."
1,1,nz retailers don’t even contactless credit car...,0,nz retailers don’t even contactless credit car...,nz retailers dont even contactless credit card...,nz retailers do not even contactless credit ca...,"[nz, retailers, do, not, even, contactless, cr...","[nz, retailers, even, contactless, credit, car..."
2,2,forever acknowledge channel help lessons ideas...,2,forever acknowledge channel help lessons ideas...,forever acknowledge channel help lessons ideas...,forever acknowledge channel help lessons ideas...,"[forever, acknowledge, channel, help, lessons,...","[forever, acknowledge, channel, help, lessons,..."
3,3,whenever go place doesn’t take apple pay doesn...,0,whenever go place doesn’t take apple pay doesn...,whenever go place doesnt take apple pay doesnt...,whenever go place does not take apple pay does...,"[whenever, go, place, does, not, take, apple, ...","[whenever, go, place, take, apple, pay, happen..."
4,4,apple pay convenient secure easy use used kore...,2,apple pay convenient secure easy use used kore...,apple pay convenient secure easy use used kore...,apple pay convenient secure easy use used kore...,"[apple, pay, convenient, secure, easy, use, us...","[apple, pay, convenient, secure, easy, use, us..."
5,5,we’ve hounding bank adopt apple pay understand...,1,we’ve hounding bank adopt apple pay understand...,weve hounding bank adopt apple pay understand ...,we have hounding bank adopt apple pay understa...,"[we, have, hounding, bank, adopt, apple, pay, ...","[hounding, bank, adopt, apple, pay, understand..."
6,6,got apple pay south africa it’s widely accepted,2,got apple pay south africa it’s widely accepted,got apple pay south africa its widely accepted,got apple pay south africa its widely accepted,"[got, apple, pay, south, africa, its, widely, ...","[got, apple, pay, south, africa, widely, accep..."
7,7,need apple pay physical credit card,1,need apple pay physical credit card,need apple pay physical credit card,need apple pay physical credit card,"[need, apple, pay, physical, credit, card]","[need, apple, pay, physical, credit, card]"
8,8,united states abundance retailers accept apple...,2,united states abundance retailers accept apple...,united states abundance retailers accept apple...,united states abundance retailers accept apple...,"[united, states, abundance, retailers, accept,...","[united, states, abundance, retailers, accept,..."
9,9,cambodia universal qr code system scan send mo...,1,cambodia universal qr code system scan send mo...,cambodia universal qr code system scan send mo...,cambodia universal qr code system scan send mo...,"[cambodia, universal, qr, code, system, scan, ...","[cambodia, universal, qr, code, system, scan, ..."

**Lemmatization**

In [ ]:
# a kind of NLTK way
df["Lemmatization"] = df["stopword_removal"].apply(
    lambda words: [word for word in words if word not in handling_stop_words])

In [ ]:
# spaCy way
import spacy
nlp = spacy.load("en_core_web_sm")

def lemmatizing(text):
    mydocument = nlp(text)
    return " ".join([token.lemma_ for token in mydocument])

df["Lemmatization"] = df["stopword_removal"].apply(lemmatizing)

ValueError: [E1041] Expected a string, Doc, or bytes as input, but got: <class 'list'>

In [ ]:
def lemmatizing(text):
    if isinstance(text, list):
        text = " ".join(text)
    mydocument = nlp(text)
    return " ".join([token.lemma_ for token in mydocument])

df["Lemmatization"] = df["stopword_removal"].apply(lemmatizing)

In [ ]:
# NLTK way
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

df["Lemmatization"] = df["stopword_removal"].apply(lambda words: [lemmatizer.lemmatize(w) for w in words])
df["lemmatized_text"] = df["Lemmatization"].apply(lambda words: ' '.join(words))

In [ ]:
df.head(10)

,rownum,Comment,Sentiment,Comment_no_emoji,Comment_lower,contractions,tokenizing,stopword_removal,Lemmatization,lemmatized_text
0,0,lets forget apple pay required brand new iphon...,1,lets forget apple pay required brand new iphon...,lets forget apple pay required brand new iphon...,let us forget apple pay required brand new iph...,"[let, us, forget, apple, pay, required, brand,...","[let, us, forget, apple, pay, required, brand,...","[let, u, forget, apple, pay, required, brand, ...",let u forget apple pay required brand new ipho...
1,1,nz retailers don’t even contactless credit car...,0,nz retailers don’t even contactless credit car...,nz retailers dont even contactless credit card...,nz retailers do not even contactless credit ca...,"[nz, retailers, do, not, even, contactless, cr...","[nz, retailers, even, contactless, credit, car...","[nz, retailer, even, contactless, credit, card...",nz retailer even contactless credit card machi...
2,2,forever acknowledge channel help lessons ideas...,2,forever acknowledge channel help lessons ideas...,forever acknowledge channel help lessons ideas...,forever acknowledge channel help lessons ideas...,"[forever, acknowledge, channel, help, lessons,...","[forever, acknowledge, channel, help, lessons,...","[forever, acknowledge, channel, help, lesson, ...",forever acknowledge channel help lesson idea e...
3,3,whenever go place doesn’t take apple pay doesn...,0,whenever go place doesn’t take apple pay doesn...,whenever go place doesnt take apple pay doesnt...,whenever go place does not take apple pay does...,"[whenever, go, place, does, not, take, apple, ...","[whenever, go, place, take, apple, pay, happen...","[whenever, go, place, take, apple, pay, happen...",whenever go place take apple pay happen often ...
4,4,apple pay convenient secure easy use used kore...,2,apple pay convenient secure easy use used kore...,apple pay convenient secure easy use used kore...,apple pay convenient secure easy use used kore...,"[apple, pay, convenient, secure, easy, use, us...","[apple, pay, convenient, secure, easy, use, us...","[apple, pay, convenient, secure, easy, use, us...",apple pay convenient secure easy use used kore...
5,5,we’ve hounding bank adopt apple pay understand...,1,we’ve hounding bank adopt apple pay understand...,weve hounding bank adopt apple pay understand ...,we have hounding bank adopt apple pay understa...,"[we, have, hounding, bank, adopt, apple, pay, ...","[hounding, bank, adopt, apple, pay, understand...","[hounding, bank, adopt, apple, pay, understand...",hounding bank adopt apple pay understand want ...
6,6,got apple pay south africa it’s widely accepted,2,got apple pay south africa it’s widely accepted,got apple pay south africa its widely accepted,got apple pay south africa its widely accepted,"[got, apple, pay, south, africa, its, widely, ...","[got, apple, pay, south, africa, widely, accep...","[got, apple, pay, south, africa, widely, accep...",got apple pay south africa widely accepted
7,7,need apple pay physical credit card,1,need apple pay physical credit card,need apple pay physical credit card,need apple pay physical credit card,"[need, apple, pay, physical, credit, card]","[need, apple, pay, physical, credit, card]","[need, apple, pay, physical, credit, card]",need apple pay physical credit card
8,8,united states abundance retailers accept apple...,2,united states abundance retailers accept apple...,united states abundance retailers accept apple...,united states abundance retailers accept apple...,"[united, states, abundance, retailers, accept,...","[united, states, abundance, retailers, accept,...","[united, state, abundance, retailer, accept, a...",united state abundance retailer accept apple p...
9,9,cambodia universal qr code system scan send mo...,1,cambodia universal qr code system scan send mo...,cambodia universal qr code system scan send mo...,cambodia universal qr code system scan send mo...,"[cambodia, universal, qr, code, system, scan, ...","[cambodia, universal, qr, code, system, scan, ...","[cambodia, universal, qr, code, system, scan, ...",cambodia universal qr code system scan send mo...

**Create CSV file**

In [ ]:
df.to_csv("prepared_sentiment_data.csv", index=False)

In [ ]:
dff = pd.read_csv("/content/prepared_sentiment_data.csv")
dff.head()

,rownum,Comment,Sentiment,Comment_no_emoji,Comment_lower,contractions,tokenizing,stopword_removal,Lemmatization,lemmatized_text
0,0,lets forget apple pay required brand new iphon...,1,lets forget apple pay required brand new iphon...,lets forget apple pay required brand new iphon...,let us forget apple pay required brand new iph...,"['let', 'us', 'forget', 'apple', 'pay', 'requi...","['let', 'us', 'forget', 'apple', 'pay', 'requi...","['let', 'u', 'forget', 'apple', 'pay', 'requir...",let u forget apple pay required brand new ipho...
1,1,nz retailers don’t even contactless credit car...,0,nz retailers don’t even contactless credit car...,nz retailers dont even contactless credit card...,nz retailers do not even contactless credit ca...,"['nz', 'retailers', 'do', 'not', 'even', 'cont...","['nz', 'retailers', 'even', 'contactless', 'cr...","['nz', 'retailer', 'even', 'contactless', 'cre...",nz retailer even contactless credit card machi...
2,2,forever acknowledge channel help lessons ideas...,2,forever acknowledge channel help lessons ideas...,forever acknowledge channel help lessons ideas...,forever acknowledge channel help lessons ideas...,"['forever', 'acknowledge', 'channel', 'help', ...","['forever', 'acknowledge', 'channel', 'help', ...","['forever', 'acknowledge', 'channel', 'help', ...",forever acknowledge channel help lesson idea e...
3,3,whenever go place doesn’t take apple pay doesn...,0,whenever go place doesn’t take apple pay doesn...,whenever go place doesnt take apple pay doesnt...,whenever go place does not take apple pay does...,"['whenever', 'go', 'place', 'does', 'not', 'ta...","['whenever', 'go', 'place', 'take', 'apple', '...","['whenever', 'go', 'place', 'take', 'apple', '...",whenever go place take apple pay happen often ...
4,4,apple pay convenient secure easy use used kore...,2,apple pay convenient secure easy use used kore...,apple pay convenient secure easy use used kore...,apple pay convenient secure easy use used kore...,"['apple', 'pay', 'convenient', 'secure', 'easy...","['apple', 'pay', 'convenient', 'secure', 'easy...","['apple', 'pay', 'convenient', 'secure', 'easy...",apple pay convenient secure easy use used kore...

In [ ]:
dff.drop(columns=["Comment_no_emoji", "Comment_lower", "contractions",
"tokenizing", "stopword_removal", "Lemmatization"], inplace=True)
dff

,rownum,Comment,Sentiment,lemmatized_text
0,0,lets forget apple pay required brand new iphon...,1,let u forget apple pay required brand new ipho...
1,1,nz retailers don’t even contactless credit car...,0,nz retailer even contactless credit card machi...
2,2,forever acknowledge channel help lessons ideas...,2,forever acknowledge channel help lesson idea e...
3,3,whenever go place doesn’t take apple pay doesn...,0,whenever go place take apple pay happen often ...
4,4,apple pay convenient secure easy use used kore...,2,apple pay convenient secure easy use used kore...
...,...,...,...,...
241108,241921,crores paid neerav modi recovered congress lea...,0,crore paid neerav modi recovered congress lead...
241109,241922,dear rss terrorist payal gawar modi killing pl...,0,dear rss terrorist payal gawar modi killing pl...
241110,241923,cover interaction forum left,1,cover interaction forum left
241111,241924,big project came india modi dream project happ...,1,big project came india modi dream project happ...
241112,241925,ever listen like gurukul discipline maintained...,2,ever listen like gurukul discipline maintained...

In [ ]:
dff["lemmatized_text"].replace("", np.nan, inplace=True)
dff.dropna(subset=["lemmatized_text"], inplace=True)
dff.reset_index(drop=True, inplace=True)

/tmp/ipython-input-97970823.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dff["lemmatized_text"].replace("", np.nan, inplace=True)

In [ ]:
dff.to_csv("prepared_sentiment_data_less_column.csv", index=False)